/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lendbooks.boundary;

import lendbooks.controller.;
import javax.swing.JComboBox;
import entity.modal.DataAccessHelper;
import books.controller.BookController;
import lendbooks.modal.DangKyMuon;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nguyen Phuong
 */
public class DangKyMuon_DocGia extends javax.swing.JFrame {
    
      DangKyMuonConTroller dangki_controller = new DangKyMuonConTroller();
      DangKyMuon dangki = new DangKyMuon();
      
      int idDangKiMuon ;
      String ngaydangki ;
      public static int MaThe = 12347 ;
    
    /**
     * Creates new form DangKyMuon_DocGia
     */
    public DangKyMuon_DocGia() {
        initComponents();
       
        dangki_controller.getListBorrowed(tableMuon);
         dangki_controller.getCombobox(boxCopyBook);
        
        
      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMuon = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boxCopyBook = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ĐẠI HỌC BÁCH KHOA HÀ NỘI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ĐĂNG KÝ MƯỢN");

        tableMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách mượn", "Tên sách", "Ngày đăng ký", "Ngày đến lấy"
            }
        ));
        tableMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMuonMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableMuon);

        jButton2.setText("Đăng ký");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hủy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày đến lấy");

        txtNgay.setToolTipText("yyyy/MM/dd");
        txtNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã sách bản sao");

        boxCopyBook.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxCopyBook.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                boxCopyBookPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                boxCopyBookPopupMenuCanceled(evt);
            }
        });
        boxCopyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCopyBookActionPerformed(evt);
            }
        });

        jButton1.setText("Xem danh sách đã đăng ký");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jButton2)
                                .addGap(112, 112, 112)
                                .addComponent(jButton3)
                                .addGap(69, 69, 69)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(boxCopyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(564, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(boxCopyBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        
//        Format format = new SimpleDateFormat("yyyy/MM/dd");
        String ngaydenlay = txtNgay.getText();
        ngaydangki =getTodayNgayThangNam();
       String  Str =  (boxCopyBook.getSelectedItem().toString());
      
       
       int MaSachMuon =Integer.parseInt( Str.substring(1,Str.length()-1));
       
       
        if(dangki_controller.RegisterBorrow(MaSachMuon, ngaydangki, ngaydenlay, MaThe)==true){
            dangki_controller.getListBorrowed(tableMuon);
             JOptionPane.showMessageDialog(this, "Đăng ký thành công");
            
        }else{
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
        
        if(dangki_controller.CancelRegisterBorrowed(idDangKiMuon)==true){
             
             dangki_controller.getListBorrowed(tableMuon);
             JOptionPane.showMessageDialog(this, "Xóa thành công");
              
         }else {
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableMuonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMuonMouseReleased
        // TODO add your handling code here:
        
         String[] dataTable = dangki.getDataTable(tableMuon);
          idDangKiMuon = Integer.parseInt(dataTable[0]);
          txtNgay.setText(dataTable[6]);
        //   ngaydangki =dataTable[5];
    }//GEN-LAST:event_tableMuonMouseReleased

    private void txtNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        dangki_controller.getListBorrowed(tableMuon);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxCopyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCopyBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCopyBookActionPerformed

    private void boxCopyBookPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_boxCopyBookPopupMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCopyBookPopupMenuCanceled

    private void boxCopyBookPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_boxCopyBookPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCopyBookPopupMenuWillBecomeInvisible

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyMuon_DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyMuon_DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyMuon_DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyMuon_DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyMuon_DocGia().setVisible(true);
            }
        });
    }
     
  public static String getTodayNgayThangNam() { //Trả về ngày tháng hôm nay dạng ngày-tháng-năm
  Date today = new Date();
  String ngay = new SimpleDateFormat("dd").format(today);
  String thang = new SimpleDateFormat("MM").format(today);
  String nam = new SimpleDateFormat("YYYY").format(today);
  return (nam + "/" + thang + "/" + ngay);

 }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxCopyBook;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableMuon;
    private javax.swing.JTextField txtNgay;
    // End of variables declaration//GEN-END:variables
}
